[package]
name = "day_1"
version = "0.1.0"
edition = "2024"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"

[dependencies]
rootcause = { workspace = true }
